### ISSUE TITLE
File uploads do not work with PHP 5.6+

### ISSUE THREAD

**Issue by jnankin** [phaxio/phaxio-php#7]
Need to start using CURLFile and have backwards compatibility for PHP 5.6+.  See this: http://stackoverflow.com/questions/25934128/curl-file-uploads-not-working-anymore-after-upgrade-from-php-5-5-to-5-6

**Comment by jpettettphaxio** [comment]
Do you have a test case for this?  Since the phaxio-php library builds the multipart payload itself, this seems to be a non-issue.

**Comment by jpettettphaxio** [comment]
Seems this is now obsoleted by the new version of this lib.
